const SHOW_FORM_MODAL = "SHOW_FORM_MODAL";
const HIDE_FORM_MODAL = "HIDE_FORM_MODAL";
const CREATE_FORM = "CREATE_FORM";
const VIEW_FORM = "VIEW_FORM";
const EDIT_FORM = "EDIT_FORM";
const REMOVE_FORM = "REMOVE_FORM";
const UPDATE_FORM = "UPDATE_FORM";
const FILL_FORM = "FILL_FORM";

export {
  SHOW_FORM_MODAL,
  HIDE_FORM_MODAL,
  CREATE_FORM,
  VIEW_FORM,
  EDIT_FORM,
  REMOVE_FORM,
  UPDATE_FORM,
  FILL_FORM
};